### ISSUE TITLE
invalid apiVersion

### ISSUE THREAD

**Issue by robrichardson13** [CircleCI-Public/kubernetes-orb#60]
Copy of https://github.com/CircleCI-Public/aws-eks-orb/issues/67 but posting here for visibility.

### Orb version
aws-eks: circleci/aws-eks@2.1.2
kubernetes: circleci/kubernetes@1.3

### What happened
We just started getting this error when running `kubectl` commands:
```sh
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

```sh
  my-job:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl version
          name: My Job
```

### Expected behavior

The `kubectl` command should work, but instead its erroring on every command.

**Comment by DanielFrank** [comment]
As I noted [here](https://github.com/CircleCI-Public/aws-eks-orb/issues/67#issuecomment-1116767590), the issue is that the latest kubectl deprecated `client.authentication.k8s.io/v1alpha1` but `aws-eks/update-kubeconfig-with-authenticator` still uses it.

Short-term solution is to run `kubernetes/install` with `kubectl-version` set. Long-term solution is for `circleci/aws-eks` to fix its orb and not use the deprecated API command.
